#!/usr/bin/env python3
"""Calculate LIBERO rollout success rates from evaluation JSON/JSONL records."""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable


SUITES = [
    "libero_goal",
    "libero_spatial",
    "libero_object",
    "libero_10",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path, help="Input JSON or JSONL file.")
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional path to save the summary JSON.",
    )
    parser.add_argument(
        "--include-unknown-suite",
        action="store_true",
        help="Also report records whose suite is not in the four standard suites.",
    )
    return parser.parse_args()


def load_records(path: Path) -> list[dict[str, Any]]:
    """Load either a JSON list/dict or JSONL records."""
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return []

    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        records = []
        for line_number, line in enumerate(text.splitlines(), start=1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSONL at line {line_number}: {exc}") from exc
            if isinstance(record, dict):
                records.append(record)
        return records

    if isinstance(data, list):
        return [record for record in data if isinstance(record, dict)]

    if isinstance(data, dict):
        # Evaluation files generated by the rollout script store records in
        # separate top-level success/failure lists.
        success_records = data.get("success")
        failure_records = data.get("failure")
        if isinstance(success_records, list) or isinstance(failure_records, list):
            records = []
            for record in success_records or []:
                if isinstance(record, dict):
                    item = dict(record)
                    item["_result_hint"] = "success"
                    records.append(item)
            for record in failure_records or []:
                if isinstance(record, dict):
                    item = dict(record)
                    item["_result_hint"] = "failure"
                    records.append(item)
            return records

        # Support common wrappers such as {"results": [...]}.
        for key in ("results", "records", "episodes", "rollouts", "evaluations", "data"):
            if isinstance(data.get(key), list):
                return [record for record in data[key] if isinstance(record, dict)]
        return [data]

    raise ValueError("Input must contain a JSON object, JSON list, or JSONL records.")


def get_suite(record: dict[str, Any]) -> str | None:
    extra = record.get("extra")
    if isinstance(extra, str):
        try:
            extra = json.loads(extra)
        except json.JSONDecodeError:
            extra = None
    if isinstance(extra, dict):
        suite = extra.get("suite")
        if suite is not None:
            return normalize_suite(str(suite))
    suite = record.get("suite")
    return normalize_suite(str(suite)) if suite is not None else None


def normalize_suite(suite: str) -> str:
    suite = suite.strip().lower()
    aliases = {
        "libero-long": "libero_10",
        "libero_long": "libero_10",
        "libero-long-horizon": "libero_10",
        "libero10": "libero_10",
        "libero-goal": "libero_goal",
        "libero-spatial": "libero_spatial",
        "libero-object": "libero_object",
    }
    return aliases.get(suite, suite)


def get_success(record: dict[str, Any]) -> bool | None:
    result_hint = record.get("_result_hint")
    if result_hint == "success":
        return True
    if result_hint == "failure":
        return False

    video = str(record.get("video", ""))
    filename = Path(video).name.lower()
    stem = Path(filename).stem

    if re.search(r"(?:^|[_-])success(?:[_-]|$)", stem):
        return True
    if re.search(r"(?:^|[_-])failure(?:[_-]|$)", stem):
        return False
    return None


def calculate(records: Iterable[dict[str, Any]], include_unknown: bool = False) -> dict[str, Any]:
    stats: dict[str, dict[str, int]] = defaultdict(
        lambda: {"total": 0, "success": 0, "failure": 0, "unknown_result": 0}
    )
    skipped = {
        "missing_suite": 0,
        "unknown_suite": 0,
        "unknown_result": 0,
    }
    raw_suite_values: dict[str, int] = defaultdict(int)

    for record in records:
        suite = get_suite(record)
        result = get_success(record)

        raw_extra = record.get("extra")
        if isinstance(raw_extra, dict) and raw_extra.get("suite") is not None:
            raw_suite_values[str(raw_extra["suite"])] += 1
        elif record.get("suite") is not None:
            raw_suite_values[str(record["suite"])] += 1

        if suite is None:
            skipped["missing_suite"] += 1
            continue
        if suite not in SUITES and not include_unknown:
            skipped["unknown_suite"] += 1
            continue

        stats[suite]["total"] += 1
        if result is True:
            stats[suite]["success"] += 1
        elif result is False:
            stats[suite]["failure"] += 1
        else:
            stats[suite]["unknown_result"] += 1
            skipped["unknown_result"] += 1

    summary: dict[str, Any] = {"suites": {}, "skipped": skipped}
    summary["raw_suite_values"] = dict(raw_suite_values)
    ordered_suites = SUITES + sorted(set(stats) - set(SUITES))
    for suite in ordered_suites:
        item = stats.get(suite)
        if item is None:
            item = {"total": 0, "success": 0, "failure": 0, "unknown_result": 0}

        denominator = item["success"] + item["failure"]
        item_with_rate = {
            **item,
            "success_rate": (
                item["success"] / denominator if denominator > 0 else None
            ),
        }
        summary["suites"][suite] = item_with_rate

    total_success = sum(item["success"] for item in summary["suites"].values())
    total_failure = sum(item["failure"] for item in summary["suites"].values())
    summary["overall"] = {
        "total": total_success + total_failure,
        "success": total_success,
        "failure": total_failure,
        "success_rate": (
            total_success / (total_success + total_failure)
            if total_success + total_failure > 0
            else None
        ),
    }
    return summary


def main() -> None:
    args = parse_args()
    records = load_records(args.input)
    summary = calculate(records, include_unknown=args.include_unknown_suite)

    print(json.dumps(summary, ensure_ascii=False, indent=2))
    for suite, item in summary["suites"].items():
        rate = item["success_rate"]
        rate_text = "N/A" if rate is None else f"{rate * 100:.2f}%"
        print(
            f"{suite}: {item['success']}/{item['success'] + item['failure']} "
            f"success = {rate_text}"
        )

    if args.output is not None:
        args.output.write_text(
            json.dumps(summary, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"Saved summary to: {args.output}")


if __name__ == "__main__":
    main()
